### ISSUE TITLE
Ignore by user or library path

### ISSUE THREAD

**Issue by 8a8al00ey** [everettsouthwick/Eraserr#18]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to run the script and have it ignore media removal if the request was from a specific user and/or if the media is in a specific path.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by everettsouthwick** [comment]
Thank you for the suggestion! I've thought about ways to exclude media from being deleted and I think the best approach would be to use custom tags on Radarr/Sonarr to indicate that you want that to be excluded from being deleted. I will add this to the backlog for future implementation.

**Comment by everettsouthwick** [comment]
Tag exemption has been implemented in #21. With this change, the configuration has been moved from .env to config.json to provide more structure for configuration. You can modify the services in Overseerr to add a tag for users when they request things to implement it based on the user who requested:
![image](https://github.com/everettsouthwick/Eraserr/assets/8216991/1d84be05-1ae7-44d0-89c5-8e1b62a926d2)
