### ISSUE TITLE
Disable Plex Library Refresh

### ISSUE THREAD

**Issue by kalyway101** [everettsouthwick/Eraserr#22]
**Is your feature request related to a problem? Please describe.**
Yes. I would like to have the option to NOT refresh my Plex library.

**Describe the solution you'd like**
Something in the configuration that disables library refresh

**Comment by everettsouthwick** [comment]
This has been implemented in #24. There is a new `config.json` property introduced to dictate whether the Plex library should be refreshed following completion.

```json
    "plex": {
        "base_url": "http://host.port",
        "token": "",
        "refresh": true // false if you don't want it to refresh
    },
```

**Comment by abnersnell** [comment]
Was "refresh" removed from the latest version?

**Comment by everettsouthwick** [comment]
@abnersnell I removed the functionality to refresh altogether. Is this a feature you'd like to see come back? It was a little buggy so I removed it in favor of more robust solutions that are already available (like autoscanner, or linking your radarr/sonarr with plex).

**Comment by abnersnell** [comment]
Perfect!  I use autoscan. Thank you!
