### ISSUE TITLE
free space threshold

### ISSUE THREAD

**Issue by djmoor4** [everettsouthwick/Eraserr#34]
**Is your feature request related to a problem? Please describe.**
I want to make the most of the storage capacity that I have, I want to let it fill up and only purge when free space gets down to 20% then let Eraserr do its thing 

**Describe the solution you'd like**
set a certain free space percentage to enable Eraserr deletions

**Describe alternatives you've considered**
scripts that look at drive space then make api calls for deletions 

**Additional context**

**Comment by everettsouthwick** [comment]
This is something I've considered, but it may be complex to implement. If I can achieve this, this is something I plan to add to the script.

**Comment by everettsouthwick** [comment]
This has been added as a experimental feature in #45. I recommend extensive testing in dry_run to verify it is working in your environment before enabling it in real execution mode.
